create table lancamento (id int4 generated by default as identity, dt_lancamento date not null, ds_lancamento varchar(50), tipo varchar(255) not null, vl_lancamento float8 not null check (vl_lancamento>=0), primary key (id));
create table usuario (id int4 generated by default as identity, email varchar(100), role varchar(255), senha varchar(255), primary key (id));
alter table if exists usuario add constraint UK5171l57faosmj8myawaucatdw unique (email);
